server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: MANAGEMENT-USER-SERVICE
          uri: lb://MANAGEMENT-USER-SERVICE
          predicates:
            - Path=/users/**

        - id: MANAGEMENT-RATING-SERVICE
          uri: lb://MANAGEMENT-RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: MANAGEMENT-HOTEL-SERVICE
          uri: lb://MANAGEMENT-HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
