server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema="hotelschema"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
